"""add reason to hotspots

Revision ID: 00bdfc301cb8
Revises: 0fa270ac6880
Create Date: 2026-04-23 14:55:50.440820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bdfc301cb8'
down_revision: Union[str, Sequence[str], None] = '0fa270ac6880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspots', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspots', 'reason')
    # ### end Alembic commands ###
