"""add author_avatar to hotspots

Revision ID: 0fa270ac6880
Revises: 434d27dc9325
Create Date: 2026-04-23 14:38:14.894365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa270ac6880'
down_revision: Union[str, Sequence[str], None] = '434d27dc9325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspots', sa.Column('author_avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspots', 'author_avatar')
    # ### end Alembic commands ###
