"""add author fields to hotspots

Revision ID: 434d27dc9325
Revises: afb09b029dfb
Create Date: 2026-04-23 14:28:07.216739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434d27dc9325'
down_revision: Union[str, Sequence[str], None] = 'afb09b029dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspots', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('hotspots', sa.Column('author_handle', sa.String(length=255), nullable=True))
    op.add_column('hotspots', sa.Column('author_followers', sa.Integer(), nullable=True))
    op.add_column('hotspots', sa.Column('author_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspots', 'author_verified')
    op.drop_column('hotspots', 'author_followers')
    op.drop_column('hotspots', 'author_handle')
    op.drop_column('hotspots', 'author')
    # ### end Alembic commands ###
