"""add_coin_favorite_count_to_hotspots

Revision ID: b7bc2fefd833
Revises: 00bdfc301cb8
Create Date: 2026-04-24 20:53:10.340699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bc2fefd833'
down_revision: Union[str, Sequence[str], None] = '00bdfc301cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspots', sa.Column('coin_count', sa.Integer(), nullable=True))
    op.add_column('hotspots', sa.Column('favorite_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspots', 'favorite_count')
    op.drop_column('hotspots', 'coin_count')
    # ### end Alembic commands ###
