"""add_comment_count_to_hotspots

Revision ID: c78892e7fe20
Revises: b7bc2fefd833
Create Date: 2026-04-24 21:24:25.140607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78892e7fe20'
down_revision: Union[str, Sequence[str], None] = 'b7bc2fefd833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspots', sa.Column('comment_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspots', 'comment_count')
    # ### end Alembic commands ###
